name: Auto Sync with Upstream

on:
  push:
    branches-ignore:
      - main # Exclude the main branch to avoid infinite loops

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up upstream remote
        run: |
          git remote add upstream https://github.com/eazybytes/springsecurity6.git
          git fetch upstream

      - name: Pull changes from all branches in upstream
        run: |
          git fetch origin '+refs/heads/*:refs/remotes/origin/*'
          for branch in $(git branch -r | grep -v 'HEAD' | sed 's/origin\///'); do
            git checkout $branch
            git pull origin $branch
          done

      - name: List all branches from upstream
        run: git ls-remote --heads upstream

      - name: Merge upstream changes for each branch
        run: |
          for branch in $(git ls-remote --heads upstream | cut -d'/' -f3); do
            git checkout -B $branch upstream/$branch
          done

      - name: Push changes to fork
        run: git push origin --all
